import React, { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { verifyMFACode } from '../api/mfaApi';
import Spinner from './Spinner';

interface MFAVerificationModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: (token?: string) => void;
  onError: () => void;
  actionType?: 'login' | 'password-change' | 'profile-update';
  userId: string;
}

const MFAVerificationModal: React.FC<MFAVerificationModalProps> = ({
  isOpen,
  onClose,
  onSuccess,
  onError,
  actionType = 'login',
  userId,
}) => {
  const [code, setCode] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [selectedMethod, setSelectedMethod] = useState<'email' | 'totp'>(
    'email'
  );
  const [attemptCount, setAttemptCount] = useState(0);
  const MAX_ATTEMPTS = 3;

  const handleVerifyCode = async () => {
    if (!code.trim()) {
      toast.error('Please enter the verification code');
      return;
    }

    if (code.length < 4) {
      toast.error('Verification code should be at least 4 characters');
      return;
    }

    if (attemptCount >= MAX_ATTEMPTS) {
      toast.error('Too many failed attempts. Please try again later.');
      onError();
      return;
    }

    setIsLoading(true);
    try {
      const response = await verifyMFACode({
        code,
        method: selectedMethod,
        userId,
      });

      if (response.success) {
        toast.success('Verification successful!');
        setCode('');
        setAttemptCount(0);
        setSelectedMethod('email');
        onSuccess(response.token);
      } else {
        const newAttemptCount = attemptCount + 1;
        setAttemptCount(newAttemptCount);

        if (newAttemptCount >= MAX_ATTEMPTS) {
          toast.error('Too many failed attempts. Please try again later.');
          onError();
        } else {
          toast.error(
            response.message || 'Invalid verification code. Please try again.'
          );
        }
      }
    } catch (err: any) {
      const newAttemptCount = attemptCount + 1;
      setAttemptCount(newAttemptCount);

      if (newAttemptCount >= MAX_ATTEMPTS) {
        toast.error('Too many failed attempts. Please try again later.');
        onError();
      } else {
        toast.error(
          err.response?.data?.message ||
            'Verification failed. Please try again.'
        );
      }
    } finally {
      setIsLoading(false);
    }
  };

  const handleKeyDown = async (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      await handleVerifyCode();
    }
  };

  // Reset state when modal opens
  useEffect(() => {
    if (isOpen) {
      setCode('');
      setAttemptCount(0);
      setSelectedMethod('email');
    }
  }, [isOpen]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-xl shadow-2xl p-6 md:p-8 w-full max-w-md mx-4">
        {/* Header */}
        <div className="mb-6">
          <h2 className="text-2xl font-bold text-gray-900 mb-2">
            Two-Factor Authentication
          </h2>
          <p className="text-gray-600 text-sm">
            {actionType === 'login' &&
              'Enter the verification code sent to your email or generated by your authenticator app.'}
            {actionType === 'password-change' &&
              'Please verify your identity with a 2FA code before changing your password.'}
            {actionType === 'profile-update' &&
              'Please verify your identity with a 2FA code before updating your profile.'}
          </p>
        </div>

        {/* Method Selection */}
        <div className="mb-6">
          <label className="block text-sm font-medium text-gray-700 mb-3">
            Select verification method:
          </label>
          <div className="flex gap-3">
            <label className="flex items-center cursor-pointer">
              <input
                type="radio"
                name="method"
                value="email"
                checked={selectedMethod === 'email'}
                onChange={(e) =>
                  setSelectedMethod(e.target.value as 'email' | 'totp')
                }
                className="w-4 h-4 text-blue-600"
              />
              <span className="ml-2 text-sm text-gray-700">Email</span>
            </label>
            <label className="flex items-center cursor-pointer">
              <input
                type="radio"
                name="method"
                value="totp"
                checked={selectedMethod === 'totp'}
                onChange={(e) =>
                  setSelectedMethod(e.target.value as 'email' | 'totp')
                }
                className="w-4 h-4 text-blue-600"
              />
              <span className="ml-2 text-sm text-gray-700">Authenticator</span>
            </label>
          </div>
        </div>

        {/* Code Input */}
        <div className="mb-6">
          <label
            htmlFor="mfa-code"
            className="block text-sm font-medium text-gray-700 mb-2"
          >
            {selectedMethod === 'email'
              ? 'Enter the code from your email'
              : 'Enter the 6-digit code from your authenticator app'}
          </label>
          <input
            id="mfa-code"
            type="text"
            value={code}
            onChange={(e) => setCode(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder={selectedMethod === 'email' ? 'e.g., ABC123' : '000000'}
            maxLength={10}
            className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent text-center font-mono tracking-widest text-lg"
            disabled={isLoading}
            autoFocus
          />
        </div>

        {/* Attempt Counter */}
        {attemptCount > 0 && (
          <div className="mb-6 p-3 bg-amber-50 border border-amber-200 rounded-lg">
            <p className="text-sm text-amber-800">
              Attempts remaining: {MAX_ATTEMPTS - attemptCount}/{MAX_ATTEMPTS}
            </p>
          </div>
        )}

        {/* Action Buttons */}
        <div className="flex gap-3">
          <button
            onClick={onClose}
            disabled={isLoading}
            className="flex-1 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors font-medium disabled:opacity-50 disabled:cursor-not-allowed"
          >
            Cancel
          </button>
          <button
            onClick={handleVerifyCode}
            disabled={isLoading || code.length < 4}
            className="flex-1 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors font-medium disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
          >
            {isLoading ? (
              <>
                <Spinner size="sm" />
                Verifying...
              </>
            ) : (
              'Verify'
            )}
          </button>
        </div>

        {/* Info Text */}
        <p className="mt-4 text-xs text-gray-500 text-center">
          For security reasons, this verification session is temporary and will
          expire after 10 minutes.
        </p>
      </div>
    </div>
  );
};

export default MFAVerificationModal;
